### ISSUE TITLE
deleted my example error403.cgi

### ISSUE THREAD

**Issue by gnadelwartz** [gnadelwartz/talk-with-me#1]
@raidensnake

Hi,

I deleted my example error304.cgi error handler by accident.
Is there any chache its in your webmin installtion used for testing the PCI scanner?

Thanks
Kay

**Comment by ghost** [comment]
I can check

**Comment by ghost** [comment]
Sorry the last update removed that file I don't have it.  I only have the miniserv.pl and the line in the webmin config

**Comment by ghost** [comment]
I even checked the backups and seems like it didn't backup the file.

**Comment by gnadelwartz** [comment]
thanks for help, I recreate it by hand then

**Comment by ghost** [comment]
sorry about that... It's weird the file got removed. I looked everywhere for it.

**Comment by gnadelwartz** [comment]
no problem 😁
